#%RAML 1.0
title: accountapi
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/c11629f7-85df-4071-ae51-4d3e3796cc79/api # baseUri: http://localhost:8081/api
types: 
   Account: !include datatypes/Account.raml
   AccountResponse: !include datatypes/AccountResponse.raml 
/createaccount:
  post:
    body:
      application/json:
        type: Account
    responses:
      201:
        body:
          application/json:
            type: AccountResponse
  